export const defaultQuotes = [
  {
    id: 1,
    quote: "Llegué, vi, vencí",
    originalQuote: "Veni, vidi, vici",
    author: "Julio César",
    period: "República Romana",
    context: "Tras su victoria en la batalla de Zela en el 47 a.C.",
    category: "militar",
    difficulty: "easy",
    tags: ["roma", "guerra", "victoria"],
  },
  {
    id: 2,
    quote: "Dadme un punto de apoyo y moveré el mundo",
    originalQuote: "Δῶς μοι πᾶ στῶ καὶ τὰν γᾶν κινάσω",
    author: "Arquímedes",
    period: "Grecia Helenística",
    context: "Explicando el principio de la palanca",
    category: "filosofía",
    difficulty: "medium",
    tags: ["grecia", "ciencia", "física"],
  },
  {
    id: 3,
    quote: "Solo sé que no sé nada",
    originalQuote: "Οἶδα οὐκ εἰδώς",
    author: "Sócrates",
    period: "Grecia Clásica",
    context: "Reflexión sobre el conocimiento y la sabiduría",
    category: "filosofía",
    difficulty: "easy",
    tags: ["grecia", "filosofía", "conocimiento"],
  },
  {
    id: 4,
    quote: "El hombre es un animal político",
    originalQuote: "ὁ ἄνθρωπος φύσει πολιτικὸν ζῷον",
    author: "Aristóteles",
    period: "Grecia Clásica",
    context: "De su obra 'Política'",
    category: "filosofía",
    difficulty: "medium",
    tags: ["grecia", "política", "sociedad"],
  },
  {
    id: 5,
    quote: "La suerte favorece a los audaces",
    originalQuote: "Audentes fortuna iuvat",
    author: "Virgilio",
    period: "Imperio Romano",
    context: "De la Eneida",
    category: "literatura",
    difficulty: "medium",
    tags: ["roma", "literatura", "valor"],
  },
  {
    id: 6,
    quote: "Conócete a ti mismo",
    originalQuote: "Γνῶθι σεαυτόν",
    author: "Oráculo de Delfos",
    period: "Grecia Arcaica",
    context: "Inscripción en el templo de Apolo en Delfos",
    category: "religioso",
    difficulty: "easy",
    tags: ["grecia", "religión", "autoconocimiento"],
  },
  {
    id: 7,
    quote: "El río no puede volver atrás",
    originalQuote:
      "Ποταμοῖσι τοῖσιν αὐτοῖσιν ἐμβαίνουσιν ἕτερα καὶ ἕτερα ὕδατα ἐπιρρεῖ",
    author: "Heráclito",
    period: "Grecia Arcaica",
    context: "Sobre el cambio constante de la naturaleza",
    category: "filosofía",
    difficulty: "hard",
    tags: ["grecia", "filosofía", "cambio"],
  },
  {
    id: 8,
    quote: "Prefiero ser el primero en una aldea que el segundo en Roma",
    originalQuote: "Malo esse primus in vico quam secundus Romae",
    author: "Julio César",
    period: "República Romana",
    context: "Sobre ambición y liderazgo",
    category: "político",
    difficulty: "hard",
    tags: ["roma", "ambición", "liderazgo"],
  },
  {
    id: 9,
    quote: "La experiencia es la madre de toda ciencia",
    originalQuote: "Experientia mater scientiarum",
    author: "Aristóteles",
    period: "Grecia Clásica",
    context: "Sobre el método científico",
    category: "filosofía",
    difficulty: "medium",
    tags: ["grecia", "ciencia", "conocimiento"],
  },
  {
    id: 10,
    quote: "No seré exhibida en su triunfo romano",
    originalQuote: "Non in Romano triumpho exhibebor",
    author: "Cleopatra VII",
    period: "Egipto Ptolemaico",
    context: "Antes de su suicidio para evitar ser humillada",
    category: "político",
    difficulty: "medium",
    tags: ["egipto", "política", "dignidad"],
  },
  {
    id: 11,
    quote: "En el río de la vida, nada es permanente excepto el cambio",
    originalQuote: "Πάντα ῥεῖ",
    author: "Heráclito",
    period: "Grecia Arcaica",
    context: "Filosofía sobre la naturaleza del cambio",
    category: "filosofía",
    difficulty: "medium",
    tags: ["grecia", "filosofía", "cambio"],
  },
  {
    id: 12,
    quote: "Un pueblo que no conoce su historia está condenado a repetirla",
    originalQuote: "Historia magistra vitae",
    author: "Marco Tulio Cicerón",
    period: "República Romana",
    context: "Sobre la importancia del estudio histórico",
    category: "histórico",
    difficulty: "hard",
    tags: ["roma", "historia", "aprendizaje"],
  },
];
